// 英文字典：index.html 選「EN」時載入，toEn() 先查 exact（整句對照），再依序試 rules（第一條命中的算數，
// 用一次 String.replace 套上取代字串；括號抓到的中文片段會再查一次 exact）。字典沒有、又含中文的句子才送機器翻譯。
// 規則的正規式自己用 ^…$ 定界；取代字串裡 $1… 是括號，字面上的 $ 要寫成 $$。
// 這份檔案由 scratchpad 的 gen_lang_en.py 產生：toEn() 一句只套一條規則、一次取代，句子裡可有可無的片段
// （除息、匯率、52 週高點…）沒辦法各自翻，每種組合都得是獨立的一條，所以用程式展開，不要手改展開後的那幾段。
// 「規則括號會抓到的片段」那一段的鍵不會單獨出現在畫面上，是給可有可無的括號查的（值前後的空白就是英文的空格）。
window.UI_EN = {
  exact: {
    // ---- 報頭、按鈕、通知
    "馬股每日追蹤": "Bursa Daily Tracker",
    "馬股追蹤": "Bursa Tracker",
    "更新": "Refresh",
    "重新載入最新資料": "Reload the latest data",
    "收盤價，非即時報價。僅為資訊整理，不構成投資建議。": "Closing prices, not live quotes. For information only; not investment advice.",
    "語言": "Language",
    "中文": "Chinese",
    "加入最愛": "Add to favourites",
    "關閉": "Close",
    "已更新到最新資料": "Updated to the latest data",
    "已經是最新資料": "Already up to date",
    "英文字典載入失敗": "Dictionary failed to load",
    "先用機器翻譯頂著，請確認網路後再試一次": "Using machine translation; check your connection",
    "資料載入失敗": "Failed to load data",
    "逾時": "Timed out",
    "翻譯失敗": "Translation failed",
    "翻譯中⋯": "Translating…",
    "專有名詞還原失敗": "Could not restore protected terms",
    "轉成繁體中文⋯": "Converting to Traditional Chinese…",
    "轉繁體失敗，以下是簡體原文。": "Conversion failed; the Simplified original is shown below.",
    "下方有英文原文。": "The English original is below.",
    "Error: 逾時": "Error: timed out",
    // ---- 首頁卡片：標題、副標、按鈕
    "重點": "Highlights",
    "市場快訊": "Market wrap",
    "追蹤股票最新": "Watchlist news",
    "馬股漲跌排行": "Top movers (Bursa)",
    "馬股新股 IPO": "IPOs (Bursa)",
    "媒體報導": "News",
    "Bursa 公告": "Bursa filings",
    "重點報導": "Digest",
    "收起": "Hide",
    "展開": "Show",
    "讀全文": "Full text",
    "原文": "Original",
    "即時": "Live",
    "中文報": "Chinese press",
    "中文報 · 載入中": "Chinese press · loading",
    "最近 7 天，星洲、南洋、中國報沒有提到追蹤股票的財經新聞。": "No business news on watchlist stocks in Sin Chew, Nanyang or China Press in the last 7 days.",
    "暫時連不上星洲、南洋、中國報，稍後會自動再試。": "Cannot reach Sin Chew, Nanyang or China Press right now; will retry automatically.",
    "全市場前 5 名": "Top 5 market-wide",
    "漲最多": "Top gainers",
    "跌最多": "Top losers",
    "沒有上漲的": "No gainers",
    "沒有下跌的": "No losers",
    "今天盤中": "Today intraday",
    "今天收盤": "Today's close",
    "即將上市": "Upcoming",
    "上市": "Listed",
    "今天": "Today",
    "明天": "Tomorrow",
    "IPO 價": "IPO price",
    "代號": "Code",
    "超額認購": "Oversubscribed",
    "全部是在馬來西亞交易所（Bursa Malaysia）掛牌的新股，價格單位是令吉（RM）。創業板（ACE）是給成長型中小企業的板塊，風險比主板高。": "All are new listings on Bursa Malaysia; prices are in ringgit (RM). The ACE Market is for growth-stage SMEs and carries more risk than the Main Market.",
    "全部是在馬來西亞交易所（Bursa Malaysia）掛牌的新股，價格單位是令吉（RM）。": "All are new listings on Bursa Malaysia; prices are in ringgit (RM).",
    "創業板（ACE）是給成長型中小企業的板塊，風險比主板高。": "The ACE Market is for growth-stage SMEs and carries more risk than the Main Market.",
    "馬來西亞交易所（Bursa Malaysia）主板與創業板。每列是「名稱、代號 · 行業」與「漲跌幅、每股現價（令吉）」，點一下看該股詳細資料。": "Bursa Malaysia Main and ACE Markets. Each row shows name, code · sector and % change, price per share (RM); tap for details.",
    "RM0.005 的仙股跳一格就是 +100%，沒有參考價值。": "A RM0.005 penny stock jumps +100% on a single tick, which tells you nothing.",
    // ---- IPO 板別、行業（market.py BOARD_ZH／SECTOR_ZH）
    "主板": "Main Market",
    "創業板（ACE）": "ACE Market",
    "LEAP 板（限資深投資者）": "LEAP Market (sophisticated investors only)",
    "金融": "Finance",
    "工業": "Industrial",
    "消費": "Consumer",
    "電訊媒體": "Telco & media",
    "運輸物流": "Transport",
    "科技": "Tech",
    "能源": "Energy",
    "地產": "Property",
    "種植": "Plantation",
    "建築": "Construction",
    "醫療": "Healthcare",
    "公用事業": "Utilities",
    // ---- 分頁、分類標題、表格欄位、圖表區間
    "最愛": "Favourites",
    "指數": "Index",
    "銀行": "Banks",
    "油棕": "Palm",
    "全部": "All",
    "大盤": "Market",
    "國際": "Global",
    "加密": "Crypto",
    "其他": "Other",
    "AI 馬股": "Bursa AI",
    "AI 美股": "US AI",
    "走勢·半年": "6M trend",
    "股價": "Price",
    "今日": "Today",
    "殖利率": "Yield",
    "息": "DY",
    "1個月": "1M",
    "3個月": "3M",
    "半年": "6M",
    "1年": "1Y",
    "3年": "3Y",
    "5年": "5Y",
    "（週線）": " (weekly)",
    "前收": "Prev close",
    "當日高": "Day high",
    "當日低": "Day low",
    "5 日": "5D",
    "3 個月": "3M",
    "1 年": "1Y",
    "3 年": "3Y",
    "5 年": "5Y",
    "52週高": "52w high",
    "52週低": "52w low",
    "距高點": "Off high",
    "成交量": "Volume",
    "量能倍數": "Vol. ratio",
    "市值": "Mkt cap",
    "每股淨值": "BVPS",
    "每股派息": "DPS",
    "派息率": "Payout",
    "除息日": "Ex-div date",
    "下次財報": "Next results",
    "分析師": "Analysts",
    "目標價": "Target",
    "買進": "Buy",
    "強力買進": "Strong Buy",
    "中立": "Hold",
    "賣出": "Sell",
    "強力賣出": "Strong Sell",
    "優於大盤": "Outperform",
    "落後大盤": "Underperform",
    "加碼": "Overweight",
    "減碼": "Underweight",
    // ---- 鮮果串試算
    "鮮果串（FFB）收購價試算": "FFB price calculator",
    "鮮果串價 = 毛棕櫚油價 × 出油率。CPO 價預設帶入": "FFB price = CPO price × OER. CPO defaults to the",
    "出油率": "OER",
    "CPO 價 RM/噸": "CPO price RM/t",
    "/噸": "/t",
    "RM/噸": "RM/t",
    // ---- 重點整理的列標、重點種類、空狀態
    "價格": "Price",
    "公告": "Filings",
    "報導": "News",
    "數字": "Stats",
    "留意": "Watch",
    "盤中": "Intraday",
    "收盤": "Close",
    "類股": "Sector",
    "類股持續": "Sector (ongoing)",
    "行事曆": "Calendar",
    "近三個月沒有相關報導": "No related news in the last three months",
    "沒有抓到公告": "No filings found",
    "不是單日暴跌，而是連續下跌累積出來的。": "Not a one-day crash; it built up over consecutive falls.",
    "一年來收盤的最高價。": "Highest close in a year.",
    "5% 以上的單日波動即使對加密貨幣也算大。": "A 5%+ daily move is large even for crypto.",
    "穩定幣的價格本來就該貼著 1 美元。偏離超過 0.5% 代表市場對它的兌付能力有疑慮，脫鉤時通常伴隨大量贖回。": "A stablecoin should trade at US$1. A gap above 0.5% means the market doubts its redeemability; de-pegs usually come with heavy redemptions.",
    "公債殖利率是 REIT 這類配息資產的對照基準：殖利率走高時，同樣的配息看起來就沒那麼吸引人。單日變動幅度通常不大，要看的是方向持續性。": "The bond yield is the benchmark for income assets like REITs: when it rises, the same payout looks less attractive. Daily moves are usually small; what matters is whether the direction persists.",
    "數字上升代表馬幣相對美元貶值。貶值不利外資留在馬股，也推高進口成本。": "A higher number means the ringgit weakened against the US dollar. That discourages foreign funds from staying in Bursa and raises import costs.",
    "數字上升代表馬幣相對新幣貶值。貶值不利外資留在馬股，也推高進口成本。": "A higher number means the ringgit weakened against the Singapore dollar. That discourages foreign funds from staying in Bursa and raises import costs.",
    "國際指數單日出現這個幅度時，隔日馬股開盤常被拿來對照，但兩者不必然同向。": "When a global index moves this much in a day, Bursa's next open is often compared with it, but they need not move the same way.",
    "成交量明顯高於近期均量，且收黑。放量本身只說明有大額成交，不必然是誰在急著賣。": "Volume well above the recent average, and a down close. Heavy volume only means large trades went through, not necessarily that someone is rushing to sell.",
    "財報前後價格波動通常會放大。": "Price swings usually widen around results.",
    "除息當天股價會自動扣掉配息金額，那不是下跌。": "On the ex-dividend day the price is adjusted down by the dividend; that is not a fall.",
    "今天財報": "Results today",
    "今天除息": "Ex-dividend today",
    "昨天除息": "Went ex-dividend yesterday",
    "創 52 週新低": "New 52-week low",
    "創 52 週新高": "New 52-week high",
    "創 52 週新低，且伴隨爆量": "New 52-week low on heavy volume",
    "P/B 低於 1 但 ROE 有雙位數，估值與獲利不同步": "P/B below 1 but ROE in double digits: valuation and earnings are out of step",
    // ---- 追蹤清單的名稱（純中文的）、類股重點的名稱
    "那斯達克綜合指數": "Nasdaq",
    "費城半導體指數": "PHLX Semi (SOX)",
    "標普 500": "S&P 500",
    "台灣加權指數": "TAIEX",
    "恒生指數": "Hang Seng",
    "日經 225": "Nikkei 225",
    "新加坡海峽時報指數": "Singapore STI",
    "美債 10 年期殖利率": "US 10Y yield",
    "美元兌馬幣": "USD/MYR",
    "新幣兌馬幣": "SGD/MYR",
    "比特幣 BTC": "Bitcoin (BTC)",
    "泰達幣 USDT": "Tether (USDT)",
    "台積電 ADR": "TSMC ADR",
    "毛棕櫚油 CPO": "CPO (crude palm oil)",
    "Zetrix AI（原 MyEG）": "Zetrix AI (ex-MyEG)",
    "銀行股": "Banks",
    "馬股 AI 概念股": "Bursa AI plays",
    "美股 AI 概念股": "US AI plays",
    "馬股綜合指數": "Bursa benchmark index",
    // ---- 追蹤清單的說明（watchlist.json note）
    "馬國最大銀行": "Malaysia's largest bank",
    "資產品質最佳": "Best asset quality",
    "區域布局最廣": "Widest regional footprint",
    "持有成都銀行股權": "Holds a stake in Bank of Chengdu",
    "高股息": "High dividend",
    "豐隆銀行控股母公司": "Holding company of Hong Leong Bank",
    "中型銀行": "Mid-sized bank",
    "中小企業放款為主": "Mainly SME lending",
    "純伊斯蘭銀行": "Pure Islamic bank",
    "砂拉越州政府為大股東": "Sarawak state government is a major shareholder",
    "最小型，前身為建屋信貸": "Smallest of the group; formerly Malaysia Building Society",
    "辦公樓 REIT": "Office REIT",
    "零售 (Mid Valley)": "Retail (Mid Valley)",
    "零售 (Pavilion KL)": "Retail (Pavilion KL)",
    "工業 / 物流": "Industrial / logistics",
    "雙峰塔綜合體": "Petronas Twin Towers complex",
    "營建地產，Sentral REIT 的保薦人與大股東": "Construction and property; sponsor and major shareholder of Sentral REIT",
    "美股科技股指標，全球風險偏好的風向球": "US tech benchmark; a gauge of global risk appetite",
    "半導體景氣指標，跟台股連動最深": "Semiconductor cycle gauge; moves most closely with Taiwan stocks",
    "美股大盤": "US market benchmark",
    "台股大盤": "Taiwan market benchmark",
    "港股大盤": "Hong Kong market benchmark",
    "日股大盤": "Japan market benchmark",
    "區域同儕，外資常拿來跟馬股比較": "Regional peer; foreign funds often compare it with Bursa",
    "REIT 估值的關鍵對照：它上升，高息資產就相對沒吸引力": "Key reference for REIT valuations: when it rises, high-yield assets look less attractive",
    "匯率直接影響外資進出與進口成本": "Directly affects foreign fund flows and import costs",
    "馬新兩地往來與跨境消費、匯款最直接的匯率": "The rate that matters most for Malaysia–Singapore travel, cross-border spending and remittances",
    "24 小時交易，週末也開盤。單日波動 3% 以上是常態": "Trades around the clock, weekends included. Daily moves above 3% are normal",
    "錨定 1 美元的穩定幣。看的不是漲跌，是有沒有脫鉤": "Stablecoin pegged to US$1. What matters is not the move but whether it de-pegs",
    "AI 晶片龍頭，整個 AI 資本支出的風向球": "AI chip leader; the bellwether for all AI capex",
    "客製化 AI 晶片與網路交換器": "Custom AI chips and network switches",
    "AI 晶片第二供應商": "Second-source AI chip supplier",
    "先進製程獨佔，台股權重最大": "Monopoly on leading-edge nodes; largest weight in Taiwan's index",
    "Azure 雲端與 OpenAI 最大股東": "Azure cloud; OpenAI's largest shareholder",
    "自研 TPU 與 Gemini": "In-house TPU and Gemini",
    "AI 應用軟體，估值最極端的一檔": "AI application software; the most extreme valuation of the group",
    "晶片架構授權": "Chip architecture licensing",
    "馬股最大 AI 資料中心概念股": "Bursa's largest AI data-centre play",
    "資料中心工程總包": "Data-centre EPC contractor",
    "資料中心建商": "Data-centre builder",
    "政府數位服務轉型 AI 與區塊鏈": "Government digital services pivoting to AI and blockchain",
    "半導體封測，射頻與光通訊": "Semiconductor OSAT; RF and optical",
    "半導體檢測設備": "Semiconductor inspection equipment",
    "半導體設備清洗服務": "Semiconductor equipment cleaning services",
    "半導體封測": "Semiconductor OSAT",
    "資料中心光纖骨幹": "Data-centre fibre backbone",
    "土地轉作資料中心": "Land repurposed for data centres",
    "MPOB 官方每日馬來西亞毛棕櫚油牌價": "MPOB official daily Malaysian crude palm oil price",
    // ---- 新聞來源、公告類別（news.py KLSE_PUBS、translate.py CATEGORY）
    "星洲日報": "Sin Chew Daily",
    "南洋商報": "Nanyang Siang Pau",
    "中國報": "China Press",
    "東方日報": "Oriental Daily",
    "詩華日報": "See Hua Daily",
    "超能网": "Expreview",
    "上市通函": "Listing circular",
    "權益事項": "Entitlement",
    "財務業績": "Financial results",
    "一般公告": "General announcement",
    "持股變動": "Shareholding change",
    "董事會異動": "Boardroom change",
    "年報": "Annual report",
    "致股東通函": "Circular to shareholders",
    "剛剛": "Just now",
    "昨天": "Yesterday",
    // ---- 公告標題（translate.py FILING_RULES 的固定輸出）、機構簡稱與常見譯名
    "閉市過戶通知": "Notice of book closure",
    "收益分派": "Income distribution",
    "主要股東權益通知": "Notice of substantial shareholder's interest",
    "主要股東持股變動（2016年公司法第138條）": "Change in substantial shareholder's interest (s.138 CA 2016)",
    "董事持股變動（第135條）": "Change in director's interest (s.135)",
    "股東大會：會議結果": "General meeting: outcome of meeting",
    "股東大會：股東大會通告": "General meeting: notice of AGM",
    "股票回購即時公告": "Share buy-back: immediate announcement",
    "額外上市公告／股份拆細": "Additional listing announcement / subdivision of shares",
    "末期股息": "Final dividend",
    "首次中期股息": "First interim dividend",
    "中期股息": "Interim dividend",
    "特別股息": "Special dividend",
    "單層股息": "Single-tier dividend",
    "建議續訂股份購回授權": "Proposed renewal of share buy-back authority",
    "建議就收入或交易性質的經常性關連方交易續延股東授權": "Proposed renewal of shareholders' mandate for recurrent related-party transactions",
    "更改地址": "Change of address",
    "僱員公積金局 (EPF)": "EPF",
    "退休基金局 (KWAP)": "KWAP",
    "信託局 (AmanahRaya)": "AmanahRaya",
    "國民投資公司 (PNB)": "PNB",
    "朝聖基金局": "Lembaga Tabung Haji",
    // ---- 原文彈窗
    "全文": "Full text",
    "原文對照": "Original",
    "標題": "Title",
    "內文": "Body",
    "內文（機器翻譯）": "Body (machine translation)",
    "中譯（機器翻譯）": "Chinese (machine translation)",
    "ENGLISH 原文": "ORIGINAL (ENGLISH)",
    "開啟原文網頁 →": "Open original page →",
    "開啟來源網頁 →": "Open source page →",
    // ---- 規則括號會抓到的片段（只給 capEn 查，不會單獨出現在畫面上）
    "增持": "bought",
    "減持": "sold",
    "轉讓": "transferred",
    "申報": " in ",
    "次，共": " filings",
    "次，增持": " filings bought ",
    "股、減持": " and sold ",
    "股，淨": " shares, net ",
    "，持股": ", stake ",
    "，主題集中在": ", themes: ",
    "其中": "",
    "則可在站內讀全文中譯，其餘點連結看原文": " readable in full here; the rest via the links",
    "標題見下方清單": "See the titles below",
    "業績": "results",
    "派息": "dividends",
    "併購": "M&A",
    "評等": "ratings",
    "營運": "operations",
    "人事": "people",
    "政策": "policy",
    "一個月": "1-month",
    "十日": "10-day",
    "下跌": "down",
    "上漲": "up",
    "普跌": "Broad selloff today",
    "普漲": "Broad rally today",
    "（持續第": " (",
    "天）": " days running)",
    "（已持續超過": " (over ",
    "個交易日）": " trading days now)",
    "。今天再跌，平均": ". Fell again today, average ",
    "。今天反彈，平均": ". Rebounded today, average ",
    "。幅度是這個類股平常波動的": ". That is ",
    "倍": "× this sector's usual volatility",
    "單檔波動過大，另外列出）": " moved too much on their own; listed separately)",
    "直接": "direct",
    "間接": "indirect",
    "，佔": "; stake ",
    "原因：": " Reason: ",
    "原因：增持": " Reason: acquired",
    "原因：減持": " Reason: disposed",
    "原因：轉讓": " Reason: transferred",
    "原因：其他": " Reason: other",
    "賣出股份": "sale of shares",
    "買入股份": "purchase of shares",
    "億": " ×100m",
    "萬": " ×10k",
    // ---- 人名、公司簡稱（中文報常用寫法）
    "黃天順": "Wong Thean Soon",
    "馬銀行": "Maybank",
    "大眾銀行": "Public Bank",
    "聯昌國際": "CIMB",
    "豐隆銀行": "Hong Leong Bank",
    "豐隆金融": "Hong Leong Financial Group",
    "興業銀行": "RHB Bank",
    "大馬銀行": "AMMB",
    "安聯銀行": "Alliance Bank",
    "伊斯蘭銀行": "Bank Islam",
    "艾芬銀行": "Affin Bank",
    "雲頂": "Genting",
    "國家銀行": "Bank Negara",
    "馬股": "Bursa Malaysia",
    "綜指": "KLCI",
    "令吉": "ringgit",
    "仙": "sen",
    "馬幣": "ringgit",
  },
  rules: [
    // ---- 相對時間；「來源 · 時間」（新聞清單、彈窗頁尾）（13 條）
    ["^(\\d+) 分鐘前$", "$1 min ago"],
    ["^(\\d+) 小時前$", "$1 h ago"],
    ["^(\\d+) 天前$", "$1 d ago"],
    ["^(\\d+) 個月前$", "$1 mo ago"],
    ["^(\\d+) 年前$", "$1 y ago"],
    ["^(· )?(.+?) · 剛剛$", "$1$2 · just now"],
    ["^(· )?(.+?) · (\\d+) 分鐘前$", "$1$2 · $3 min ago"],
    ["^(· )?(.+?) · (\\d+) 小時前$", "$1$2 · $3 h ago"],
    ["^(· )?(.+?) · 今天$", "$1$2 · today"],
    ["^(· )?(.+?) · 昨天$", "$1$2 · yesterday"],
    ["^(· )?(.+?) · (\\d+) 天前$", "$1$2 · $3 d ago"],
    ["^(· )?(.+?) · (\\d+) 個月前$", "$1$2 · $3 mo ago"],
    ["^(· )?(.+?) · (\\d+) 年前$", "$1$2 · $3 y ago"],
    // ---- 日期（fmtWhen）（21 條）
    ["^今天 (\\d+)/(\\d+)（日）$", "Today $1/$2 (Sun)"],
    ["^(\\d+)/(\\d+)（日） 收盤$", "$1/$2 (Sun) close"],
    ["^(\\d+)/(\\d+)（日）$", "$1/$2 (Sun)"],
    ["^今天 (\\d+)/(\\d+)（一）$", "Today $1/$2 (Mon)"],
    ["^(\\d+)/(\\d+)（一） 收盤$", "$1/$2 (Mon) close"],
    ["^(\\d+)/(\\d+)（一）$", "$1/$2 (Mon)"],
    ["^今天 (\\d+)/(\\d+)（二）$", "Today $1/$2 (Tue)"],
    ["^(\\d+)/(\\d+)（二） 收盤$", "$1/$2 (Tue) close"],
    ["^(\\d+)/(\\d+)（二）$", "$1/$2 (Tue)"],
    ["^今天 (\\d+)/(\\d+)（三）$", "Today $1/$2 (Wed)"],
    ["^(\\d+)/(\\d+)（三） 收盤$", "$1/$2 (Wed) close"],
    ["^(\\d+)/(\\d+)（三）$", "$1/$2 (Wed)"],
    ["^今天 (\\d+)/(\\d+)（四）$", "Today $1/$2 (Thu)"],
    ["^(\\d+)/(\\d+)（四） 收盤$", "$1/$2 (Thu) close"],
    ["^(\\d+)/(\\d+)（四）$", "$1/$2 (Thu)"],
    ["^今天 (\\d+)/(\\d+)（五）$", "Today $1/$2 (Fri)"],
    ["^(\\d+)/(\\d+)（五） 收盤$", "$1/$2 (Fri) close"],
    ["^(\\d+)/(\\d+)（五）$", "$1/$2 (Fri)"],
    ["^今天 (\\d+)/(\\d+)（六）$", "Today $1/$2 (Sat)"],
    ["^(\\d+)/(\\d+)（六） 收盤$", "$1/$2 (Sat) close"],
    ["^(\\d+)/(\\d+)（六）$", "$1/$2 (Sat)"],
    // ---- 卡片副標、按鈕、圖表讀數、試算（37 條）
    ["^顯示更多（共 (\\d+) 則）$", "Show more ($1 total)"],
    ["^只看前 (\\d+) 則$", "Show first $1"],
    ["^顯示全部 (\\d+) 條$", "Show all $1"],
    ["^只看前 (\\d+) 條$", "Show first $1"],
    ["^(\\d+) 條 · 截至 (\\S+)$", "$1 items · $2"],
    ["^大盤最新 (\\d+) 則 · 即時$", "Latest $1 · live"],
    ["^大盤最新 (\\d+) 則$", "Latest $1"],
    ["^中文報最新 (\\d+) 則 · 即時$", "Chinese press · $1 · live"],
    ["^中文報最新 (\\d+) 則$", "Chinese press · $1"],
    ["^等 (\\d+) 檔$", "+$1 more"],
    ["^新聞 ([\\d/: ]+) 更新$", "News $1"],
    ["^資料時間 ([^一-鿿]+)$", "Data as of $1"],
    ["^Error: 回應 (\\d+)$", "Error: HTTP $1"],
    ["^回應 (\\d+)$", "HTTP $1"],
    ["^翻譯失敗（(.+?)）。下方有英文原文。$", "Translation failed ($1). The English original is below."],
    ["^今天盤中 (\\S+)$", "Today intraday $1"],
    ["^(· )?市值 RM(\\S+)$", "$1Mkt cap RM$2"],
    ["^即將上市 (\\d+) 檔$", "$1 upcoming"],
    ["^最近上市 · 上市後表現（(\\d+) 檔中 (\\d+) 檔跌破 IPO 價）$", "Recent listings · since IPO ($2 of $1 below IPO price)"],
    ["^(\\d+) 天後$", "In $1 days"],
    ["^現價 (\\S+)$", "Now $1"],
    ["^([\\d.]+) 倍$", "$1x"],
    ["^(· )?最後成交 ([^一-鿿]+)$", "$1Last trade $2"],
    ["^(· )?即時報價 ([^一-鿿]+)$", "$1Live quote $2"],
    ["^最新 (\\S+) ·$", "Latest $1 ·"],
    ["^區間 (\\S+) → (\\S+) · (\\d+) 個交易日 ·$", "$1 → $2 · $3 trading days ·"],
    ["^區間 (\\S+) → (\\S+) · (\\d+) 週 ·$", "$1 → $2 · $3 weeks ·"],
    ["^([^一-鿿]+) · 息 (\\S+)$", "$1 · DY $2"],
    ["^息 (\\S+)$", "DY $1"],
    ["^1個月 (\\S+)$", "1M $1"],
    ["^([^一-鿿]+?) · RM/噸$", "$1 · RM/t"],
    ["^([\\d,.]+) RM/噸$", "$1 RM/t"],
    ["^用 (\\d+) 日均價$", "Use $1-day average"],
    ["^用當日價 ([\\d,.]+)$", "Use today's price $1"],
    ["^(\\d+) 日均價 RM ([\\d,.]+)$", "$1-day average RM $2"],
    ["^（MPOB 官方牌價每日加總 ÷ (\\d+)）。$", "(sum of MPOB daily official prices ÷ $1)."],
    ["^(.+?) · 載入中$", "$1 · loading"],
    // ---- 漲跌排行的說明（2 條）
    ["^馬來西亞交易所（Bursa Malaysia）主板與創業板。每列是「名稱、代號 · 行業」與「漲跌幅、每股現價（令吉）」，點一下看該股詳細資料。 只比較股價 RM0\\.20、市值 RM2 億以上的 ([\\d,]+) 檔（共 ([\\d,]+) 檔）： RM0\\.005 的仙股跳一格就是 \\+100%，沒有參考價值。$", "Bursa Malaysia Main and ACE Markets. Each row shows name, code · sector and % change, price per share (RM); tap for details. Only stocks priced above RM0.20 with market cap above RM200m are compared ($1 of $2 stocks): a RM0.005 penny stock jumps +100% on a single tick, which tells you nothing."],
    ["^馬來西亞交易所（Bursa Malaysia）主板與創業板。每列是「名稱、代號 · 行業」與「漲跌幅、每股現價（令吉）」，點一下看該股詳細資料。 只比較股價 RM0\\.20、市值 RM2 億以上的股票： RM0\\.005 的仙股跳一格就是 \\+100%，沒有參考價值。$", "Bursa Malaysia Main and ACE Markets. Each row shows name, code · sector and % change, price per share (RM); tap for details. Only stocks priced above RM0.20 with market cap above RM200m are compared: a RM0.005 penny stock jumps +100% on a single tick, which tells you nothing."],
    // ---- IPO 卡片的認購、集資、市值（8 條）
    ["^(· )?集資 RM(\\S+) (億|萬) · 上市市值 RM(\\S+) (億|萬)$", "$1Raising RM$2$3 · listing mkt cap RM$4$5"],
    ["^認購 (\\S*)–(\\S*) · 集資 RM(\\S+) (億|萬) · 上市市值 RM(\\S+) (億|萬)$", "Subscription $1–$2 · raising RM$3$4 · listing mkt cap RM$5$6"],
    ["^(· )?集資 RM(\\S+) (億|萬)$", "$1Raising RM$2$3"],
    ["^(· )?上市市值 RM(\\S+) (億|萬)$", "$1Listing mkt cap RM$2$3"],
    ["^認購 (\\S*)–(\\S*) · 集資 RM(\\S+) (億|萬)$", "Subscription $1–$2 · raising RM$3$4"],
    ["^認購 (\\S*)–(\\S*) · 上市市值 RM(\\S+) (億|萬)$", "Subscription $1–$2 · listing mkt cap RM$3$4"],
    ["^認購 (\\S*)–(\\S*) · 超額認購$", "Subscription $1–$2 · oversubscribed"],
    ["^認購 (\\S*)–(\\S*)$", "Subscription $1–$2"],
    // ---- 類股重點（analyze.py _sector_trends）（11 條）
    ["^(一個月|十日)平均 ([-+][\\d.]+%)，(\\d+) 檔全數(下跌|上漲)(?:(（持續第|（已持續超過) (\\d+) (天）|個交易日）))?$", "$1 average $2, all $3 $4$5$6$7"],
    ["^(一個月|十日)平均 ([-+][\\d.]+%)，(\\d+) 檔中 (\\d+) 檔(下跌|上漲)(?:(（持續第|（已持續超過) (\\d+) (天）|個交易日）))?$", "$1 average $2, $4 of $3 $5$6$7$8"],
    ["^單日(普跌|普漲)，平均 ([-+][\\d.]+%)，(\\d+) 檔中 (\\d+) 檔(下跌|上漲)$", "$1, average $2, $4 of $3 $5"],
    ["^(跌最多|漲最多)：([^。（、]+? [-+][\\d.]+%)、([^。（、]+? [-+][\\d.]+%)$", "$1: $2, $3"],
    ["^(跌最多|漲最多)：([^。（、]+? [-+][\\d.]+%)、([^。（、]+? [-+][\\d.]+%)（([^、（）]+)、([^、（）]+) 單檔波動過大，另外列出）$", "$1: $2, $3 ($4 and $5 moved too much on their own; listed separately)"],
    ["^(跌最多|漲最多)：([^。（、]+? [-+][\\d.]+%)、([^。（、]+? [-+][\\d.]+%)（([^、（）]+) 單檔波動過大，另外列出）$", "$1: $2, $3 ($4 moved too much on its own; listed separately)"],
    ["^(跌最多|漲最多)：([^。（、]+? [-+][\\d.]+%)$", "$1: $2"],
    ["^(跌最多|漲最多)：([^。（、]+? [-+][\\d.]+%)（([^、（）]+)、([^、（）]+) 單檔波動過大，另外列出）$", "$1: $2 ($3 and $4 moved too much on their own; listed separately)"],
    ["^(跌最多|漲最多)：([^。（、]+? [-+][\\d.]+%)（([^、（）]+) 單檔波動過大，另外列出）$", "$1: $2 ($3 moved too much on its own; listed separately)"],
    ["^(跌最多|漲最多)：([^。（]+)(?:(。今天再跌，平均|。今天反彈，平均) ([-+][\\d.]+%))?(?:(。幅度是這個類股平常波動的) ([\\d.]+) (倍))?$", "$1: $2$3$4$5$6$7"],
    ["^(跌最多|漲最多)：([^。（]+)(?:(。今天再跌，平均|。今天反彈，平均) ([-+][\\d.]+%))?(?:(。幅度是這個類股平常波動的) ([\\d.]+) (倍))?（([^（）]+?) (單檔波動過大，另外列出）)$", "$1: $2$3$4$5$6$7 ($8$9"],
    // ---- 個股重點（analyze.py analyse）（43 條）
    ["^偏離 1 美元 ([-+][\\d.]+%)（([\\d.]+)）$", "$1 off the US$$1 peg ($2)"],
    ["^單日重挫 ([-+][\\d.]+%)$", "Plunged $1 today"],
    ["^單日大漲 ([-+][\\d.]+%)$", "Surged $1 today"],
    ["^單日下跌 ([-+][\\d.]+%)$", "Down $1 today"],
    ["^單日上漲 ([-+][\\d.]+%)$", "Up $1 today"],
    ["^單日 ([-+][\\d.]+%)$", "Today $1"],
    ["^美債殖利率 ([-+][\\d.]+%) 至 ([\\d.]+)(\\S*)$", "US 10Y yield $1 to $2$3"],
    ["^馬幣兌美元走貶 ([-+][\\d.]+%)$", "Ringgit weakened $1 vs USD"],
    ["^馬幣兌美元走升 ([-+][\\d.]+%)$", "Ringgit strengthened $1 vs USD"],
    ["^馬幣兌新幣走貶 ([-+][\\d.]+%)$", "Ringgit weakened $1 vs SGD"],
    ["^馬幣兌新幣走升 ([-+][\\d.]+%)$", "Ringgit strengthened $1 vs SGD"],
    ["^創 52 週新低 ([\\d,.]+)((?: \\S+)?)$", "New 52-week low $1$2"],
    ["^創 52 週新高 ([\\d,.]+)$", "New 52-week high $1"],
    ["^一個月累計 ([-+][\\d.]+%)$", "1-month cumulative $1"],
    ["^五日累計 ([-+][\\d.]+%)$", "5-day cumulative $1"],
    ["^跑輸大盤 ([\\d.]+) 個百分點$", "Underperformed the market by $1 pts"],
    ["^跑贏大盤 ([\\d.]+) 個百分點$", "Outperformed the market by $1 pts"],
    ["^爆量下跌，成交量是均量的 ([\\d.]+) 倍$", "Heavy-volume fall; volume $1× average"],
    ["^成交量放大 ([\\d.]+) 倍$", "Volume up $1×"],
    ["^成交量放大 ([\\d.]+)x$", "Volume $1× average"],
    ["^(\\d+) 天後財報$", "Results in $1 days"],
    ["^(\\d+) 天後除息$", "Ex-dividend in $1 days"],
    ["^大股東減持 ([\\d,]+) 股$", "Major shareholder sold $1 shares"],
    ["^大股東增持 ([\\d,]+) 股$", "Major shareholder bought $1 shares"],
    ["^董事減持 ([\\d,]+) 股$", "Director sold $1 shares"],
    ["^董事增持 ([\\d,]+) 股$", "Director bought $1 shares"],
    ["^CPO 一個月下跌 ([-+][\\d.]+%)$", "CPO down $1 over one month"],
    ["^CPO 一個月上漲 ([-+][\\d.]+%)$", "CPO up $1 over one month"],
    ["^大盤今日 ([-+][\\d.]+%)，這檔 ([-+][\\d.]+%)。差距這麼大通常是個股自己的事。$", "Market $1 today, this stock $2. A gap this wide is usually stock-specific."],
    ["^距 52 週高點 ([\\d.]+%)。跌破前低代表過去一年在這個價位買進的人全部套牢。$", "$1 below the 52-week high. Breaking the prior low means everyone who bought in the past year is under water."],
    ["^(\\d+) 日均價 RM ([\\d,.]+)/噸，鮮果串收購價會跟著動。$", "$1-day average RM $2/t; FFB purchase prices will follow."],
    ["^公告：季度綜合業績報告（財務期間至 (\\S+)）$", "Filing: quarterly results (period ended $1)"],
    ["^公告：([^一-鿿]+?) — 閉市過戶通知$", "Filing: $1 — notice of book closure"],
    ["^公告：閉市過戶通知$", "Filing: notice of book closure"],
    ["^公告：收益分派$", "Filing: income distribution"],
    ["^公告：末期股息$", "Filing: final dividend"],
    ["^公告：首次中期股息$", "Filing: first interim dividend"],
    ["^公告：股票回購即時公告$", "Filing: share buy-back (immediate announcement)"],
    ["^([^、。]+?)。這是法人申報的持股異動，不必然代表看法改變。$", "$1. An institutional shareholding filing; not necessarily a change of view."],
    ["^([^、。]+?)、([^、。]+?)。這是法人申報的持股異動，不必然代表看法改變。$", "$1, $2. An institutional shareholding filing; not necessarily a change of view."],
    ["^([^、。]+?)、([^、。]+?)等 (\\d+) 筆。這是法人申報的持股異動，不必然代表看法改變。$", "$1, $2 and others ($3 filings). An institutional shareholding filing; not necessarily a change of view."],
    ["^([^、。]+?)。董事或個人本人買賣自家股票，跟法人調整部位性質不同。$", "$1. A director or individual trading their own company's shares, which differs from an institution adjusting positions."],
    ["^([^、。]+?)、([^、。]+?)。董事或個人本人買賣自家股票，跟法人調整部位性質不同。$", "$1, $2. A director or individual trading their own company's shares, which differs from an institution adjusting positions."],
    // ---- 訊號籤（fetch.py flags）（5 條）
    ["^距 52 週高點 ([-+]?[\\d.]+%)$", "$1 from 52-week high"],
    ["^P/B ([\\d.]+)（低於帳面淨值）$", "P/B $1 (below book value)"],
    ["^ROE 偏低 ([\\d.]+%)$", "Low ROE $1"],
    ["^派息率 (\\d+%)（高於盈餘）$", "Payout $1 (exceeds earnings)"],
    ["^(\\S+) 除息 (\\S+)$", "Ex-dividend $2 on $1"],
    // ---- 重點整理：價格（digest.py）（10 條）
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，三個月 ([-+][\\d.]+%)。$", "Closed at $2$3 on $1, $4 today. 1-month $5, 3-month $6."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，三個月 ([-+][\\d.]+%)。距 52 週高點 ([\\d,.]+) 還有 ([\\d.]+%)。$", "Closed at $2$3 on $1, $4 today. 1-month $5, 3-month $6. $8 below the 52-week high of $7."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，三個月 ([-+][\\d.]+%)。換算馬幣約 RM ([\\d,.]+)（匯率 ([\\d.]+)）。$", "Closed at $2$3 on $1, $4 today. 1-month $5, 3-month $6. ≈ RM $7 (at $8)."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，三個月 ([-+][\\d.]+%)。換算馬幣約 RM ([\\d,.]+)（匯率 ([\\d.]+)）。距 52 週高點 ([\\d,.]+) 還有 ([\\d.]+%)。$", "Closed at $2$3 on $1, $4 today. 1-month $5, 3-month $6. ≈ RM $7 (at $8). $10 below the 52-week high of $9."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，其中 (\\S+) 除息 ([\\d,.]+) 佔約 ([\\d.]+) 個百分點，不是實際下跌，三個月 ([-+][\\d.]+%)。$", "Closed at $2$3 on $1, $4 today. 1-month $5, of which the $6 ex-dividend of $7 accounts for about $8 pts (not a real fall), 3-month $9."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，其中 (\\S+) 除息 ([\\d,.]+) 佔約 ([\\d.]+) 個百分點，不是實際下跌，三個月 ([-+][\\d.]+%)。距 52 週高點 ([\\d,.]+) 還有 ([\\d.]+%)。$", "Closed at $2$3 on $1, $4 today. 1-month $5, of which the $6 ex-dividend of $7 accounts for about $8 pts (not a real fall), 3-month $9. $11 below the 52-week high of $10."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，其中 (\\S+) 除息 ([\\d,.]+) 佔約 ([\\d.]+) 個百分點，不是實際下跌，三個月 ([-+][\\d.]+%)。換算馬幣約 RM ([\\d,.]+)（匯率 ([\\d.]+)）。$", "Closed at $2$3 on $1, $4 today. 1-month $5, of which the $6 ex-dividend of $7 accounts for about $8 pts (not a real fall), 3-month $9. ≈ RM $10 (at $11)."],
    ["^(\\S+) 收 ([\\d,.]+)((?: (?:USD|%))?)、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，其中 (\\S+) 除息 ([\\d,.]+) 佔約 ([\\d.]+) 個百分點，不是實際下跌，三個月 ([-+][\\d.]+%)。換算馬幣約 RM ([\\d,.]+)（匯率 ([\\d.]+)）。距 52 週高點 ([\\d,.]+) 還有 ([\\d.]+%)。$", "Closed at $2$3 on $1, $4 today. 1-month $5, of which the $6 ex-dividend of $7 accounts for about $8 pts (not a real fall), 3-month $9. ≈ RM $10 (at $11). $13 below the 52-week high of $12."],
    ["^(\\S+) 收 ([\\d,.]+) RM/噸、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，三個月 ([-+][\\d.]+%)。$", "Closed at $2 RM/t on $1, $3 today. 1-month $4, 3-month $5."],
    ["^(\\S+) 收 ([\\d,.]+) RM/噸、單日 ([-+][\\d.]+%)。一個月 ([-+][\\d.]+%)，三個月 ([-+][\\d.]+%)。距 52 週高點 ([\\d,.]+) 還有 ([\\d.]+%)。$", "Closed at $2 RM/t on $1, $3 today. 1-month $4, 3-month $5. $7 below the 52-week high of $6."],
    // ---- 重點整理：公告（digest.py）（7 條）
    ["^((?:\\S+ )?)(.+?) (?:(申報) (\\d+) (次，共))?(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。$", "$1$2 $6 $7 shares$3$4$5$8$9."],
    ["^((?:\\S+ )?)(.+?) (申報) (\\d+) (次，增持) ([\\d,]+) (股、減持) ([\\d,]+) (股，淨)(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。$", "$1$2$3$4$5$6$7$8$9$10 $11 shares$12$13."],
    ["^((?:\\S+ )?)(.+?) (?:(申報) (\\d+) (次，共))?(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。 ((?:\\S+ )?)(.+?) (?:(申報) (\\d+) (次，共))?(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。$", "$1$2 $6 $7 shares$3$4$5$8$9. $10$11 $15 $16 shares$12$13$14$17$18."],
    ["^((?:\\S+ )?)(.+?) (?:(申報) (\\d+) (次，共))?(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。 ((?:\\S+ )?)(.+?) (申報) (\\d+) (次，增持) ([\\d,]+) (股、減持) ([\\d,]+) (股，淨)(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。$", "$1$2 $6 $7 shares$3$4$5$8$9. $10$11$12$13$14$15$16$17$18$19 $20 shares$21$22."],
    ["^((?:\\S+ )?)(.+?) (申報) (\\d+) (次，增持) ([\\d,]+) (股、減持) ([\\d,]+) (股，淨)(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。 ((?:\\S+ )?)(.+?) (?:(申報) (\\d+) (次，共))?(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。$", "$1$2$3$4$5$6$7$8$9$10 $11 shares$12$13. $14$15 $19 $20 shares$16$17$18$21$22."],
    ["^((?:\\S+ )?)(.+?) (申報) (\\d+) (次，增持) ([\\d,]+) (股、減持) ([\\d,]+) (股，淨)(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。 ((?:\\S+ )?)(.+?) (申報) (\\d+) (次，增持) ([\\d,]+) (股、減持) ([\\d,]+) (股，淨)(增持|減持) ([\\d,]+) 股(?:(，持股) ([^，。]+?))?。$", "$1$2$3$4$5$6$7$8$9$10 $11 shares$12$13. $14$15$16$17$18$19$20$21$22$23 $24 shares$25$26."],
    ["^最近 (\\d+) 則公告都沒有可抓取的內文，標題見下方清單。$", "None of the last $1 filings had retrievable text; see the titles below."],
    // ---- 重點整理：報導（digest.py）（5 條）
    ["^近三個月 (\\d+) 則(?:(，主題集中在)([^（）。]+))?。(?:(其中) (\\d+) (則可在站內讀全文中譯，其餘點連結看原文)|(標題見下方清單))。$", "$1 articles in the last three months$2$3. $4$5$6$7."],
    ["^近三個月 (\\d+) 則(?:(，主題集中在)([^（）。]+))?（([^、（）。]+)）。(?:(其中) (\\d+) (則可在站內讀全文中譯，其餘點連結看原文)|(標題見下方清單))。$", "$1 articles in the last three months$2$3 ($4). $5$6$7$8."],
    ["^近三個月 (\\d+) 則(?:(，主題集中在)([^（）。]+))?（([^、（）。]+)、([^、（）。]+)）。(?:(其中) (\\d+) (則可在站內讀全文中譯，其餘點連結看原文)|(標題見下方清單))。$", "$1 articles in the last three months$2$3 ($4, $5). $6$7$8$9."],
    ["^近三個月 (\\d+) 則(?:(，主題集中在)([^（）。]+))?（([^、（）。]+)、([^、（）。]+)、([^、（）。]+)）。(?:(其中) (\\d+) (則可在站內讀全文中譯，其餘點連結看原文)|(標題見下方清單))。$", "$1 articles in the last three months$2$3 ($4, $5, $6). $7$8$9$10."],
    ["^近三個月 (\\d+) 則(?:(，主題集中在)([^（）。]+))?（([^、（）。]+)、([^、（）。]+)、([^、（）。]+)、([^、（）。]+)）。(?:(其中) (\\d+) (則可在站內讀全文中譯，其餘點連結看原文)|(標題見下方清單))。$", "$1 articles in the last three months$2$3 ($4, $5, $6, $7). $8$9$10$11."],
    // ---- 重點整理：數字（digest.py）（8 條）
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、每股淨值 ([\\d,.]+)。$", "P/B $1, P/E $2, ROE $3, BVPS $4."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、每股淨值 ([\\d,.]+)、分析師目標價 (.+?)。$", "P/B $1, P/E $2, ROE $3, BVPS $4, analyst target $5."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、派息率 ([\\d.,%]+)、每股淨值 ([\\d,.]+)。$", "P/B $1, P/E $2, ROE $3, payout $4, BVPS $5."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、派息率 ([\\d.,%]+)、每股淨值 ([\\d,.]+)、分析師目標價 (.+?)。$", "P/B $1, P/E $2, ROE $3, payout $4, BVPS $5, analyst target $6."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、殖利率 ([\\d.,%]+)、每股淨值 ([\\d,.]+)。$", "P/B $1, P/E $2, ROE $3, yield $4, BVPS $5."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、殖利率 ([\\d.,%]+)、每股淨值 ([\\d,.]+)、分析師目標價 (.+?)。$", "P/B $1, P/E $2, ROE $3, yield $4, BVPS $5, analyst target $6."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、殖利率 ([\\d.,%]+)、派息率 ([\\d.,%]+)、每股淨值 ([\\d,.]+)。$", "P/B $1, P/E $2, ROE $3, yield $4, payout $5, BVPS $6."],
    ["^P/B ([\\d,.]+)、P/E ([\\d,.]+)、ROE ([\\d.,%]+)、殖利率 ([\\d.,%]+)、派息率 ([\\d.,%]+)、每股淨值 ([\\d,.]+)、分析師目標價 (.+?)。$", "P/B $1, P/E $2, ROE $3, yield $4, payout $5, BVPS $6, analyst target $7."],
    // ---- 重點整理：留意（digest.py）（11 條）
    ["^下次財報 (\\S+)。$", "Next results $1."],
    ["^ROE 僅 ([\\d.]+)%，賺錢效率偏低。$", "ROE only $1%, weak profitability."],
    ["^ROE 僅 ([\\d.]+)%，賺錢效率偏低；下次財報 (\\S+)。$", "ROE only $1%, weak profitability; next results $2."],
    ["^P/B 低於 1 但 ROE 有雙位數，估值與獲利不同步。$", "P/B below 1 but ROE in double digits: valuation and earnings out of step."],
    ["^P/B 低於 1 但 ROE 有雙位數，估值與獲利不同步；下次財報 (\\S+)。$", "P/B below 1 but ROE in double digits: valuation and earnings out of step; next results $1."],
    ["^派息率 (\\d+)%，高於當年盈餘。$", "Payout $1% exceeds this year's earnings."],
    ["^派息率 (\\d+)%，高於當年盈餘；下次財報 (\\S+)。$", "Payout $1% exceeds this year's earnings; next results $2."],
    ["^派息率 (\\d+)%，高於當年盈餘；ROE 僅 ([\\d.]+)%，賺錢效率偏低。$", "Payout $1% exceeds this year's earnings; ROE only $2%, weak profitability."],
    ["^派息率 (\\d+)%，高於當年盈餘；ROE 僅 ([\\d.]+)%，賺錢效率偏低；下次財報 (\\S+)。$", "Payout $1% exceeds this year's earnings; ROE only $2%, weak profitability; next results $3."],
    ["^派息率 (\\d+)%，高於當年盈餘；P/B 低於 1 但 ROE 有雙位數，估值與獲利不同步。$", "Payout $1% exceeds this year's earnings; P/B below 1 but ROE in double digits: valuation and earnings out of step."],
    ["^派息率 (\\d+)%，高於當年盈餘；P/B 低於 1 但 ROE 有雙位數，估值與獲利不同步；下次財報 (\\S+)。$", "Payout $1% exceeds this year's earnings; P/B below 1 but ROE in double digits: valuation and earnings out of step; next results $2."],
    // ---- 公告標題（translate.py FILING_RULES）＋合併後的「（N 則）」（15 條）
    ["^主要股東持股變動（2016年公司法第138條）— (.+?)（(\\d+) 則）$", "Substantial shareholder's interest (s.138 CA 2016) — $1 ($2)"],
    ["^主要股東持股變動（2016年公司法第138條）— (.+?)$", "Substantial shareholder's interest (s.138 CA 2016) — $1"],
    ["^主要股東持股變動（2016年公司法第138條）（(\\d+) 則）$", "Substantial shareholder's interest (s.138 CA 2016) ($1)"],
    ["^季度綜合業績報告（財務期間至 (\\S+)）$", "Quarterly results (period ended $1)"],
    ["^董事持股變動（第135條）— (.+?)$", "Director's interest (s.135) — $1"],
    ["^([^一-鿿]+?) — 閉市過戶通知$", "$1 — notice of book closure"],
    ["^企業簡報 ([^一-鿿]+?)$", "Corporate presentation $1"],
    ["^年報([^一-鿿]+?)$", "Annual report$1"],
    ["^股東大會：會議結果([^一-鿿]+?)$", "General meeting: outcome of meeting$1"],
    ["^董事會人事變動([^一-鿿]+?)$", "Change in boardroom$1"],
    ["^新聞稿 ([^一-鿿]+?)$", "Press release $1"],
    ["^上市證券交易([^一-鿿]+?)（(\\d+) 則）$", "Dealings in listed securities$1 ($2)"],
    ["^上市證券交易([^一-鿿]+?)$", "Dealings in listed securities$1"],
    ["^股票回購即時公告（(\\d+) 則）$", "Share buy-back: immediate announcement ($1)"],
    ["^額外上市公告／股份拆細（(\\d+) 則）$", "Additional listing announcement / subdivision of shares ($1)"],
    // ---- 持股變動公告的內文（news.py）（8 條）
    ["^(.+?) 於 (\\S+) (增持|減持|轉讓) ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。$", "$1 $3 $4 shares on $2 ($5). Holds $6 shares after the change$7$8$9."],
    ["^(.+?) 於 (\\S+) (增持|減持|轉讓) ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。 (原因：(?:增持|減持|轉讓|其他)?)(.*?)。$", "$1 $3 $4 shares on $2 ($5). Holds $6 shares after the change$7$8$9.$10$11."],
    ["^(.+?) 於 (\\S+) 其他 ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。$", "$1: other change of $3 shares on $2 ($4). Holds $5 shares after the change$6$7$8."],
    ["^(.+?) 於 (\\S+) 其他 ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。 (原因：(?:增持|減持|轉讓|其他)?)(.*?)。$", "$1: other change of $3 shares on $2 ($4). Holds $5 shares after the change$6$7$8.$9$10."],
    ["^(\\d+/\\d+)：(.+?) 於 (\\S+) (增持|減持|轉讓) ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。$", "$1: $2 $4 $5 shares on $3 ($6). Holds $7 shares after the change$8$9$10."],
    ["^(\\d+/\\d+)：(.+?) 於 (\\S+) (增持|減持|轉讓) ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。 (原因：(?:增持|減持|轉讓|其他)?)(.*?)。$", "$1: $2 $4 $5 shares on $3 ($6). Holds $7 shares after the change$8$9$10.$11$12."],
    ["^(\\d+/\\d+)：(.+?) 於 (\\S+) 其他 ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。$", "$1: $2: other change of $4 shares on $3 ($5). Holds $6 shares after the change$7$8$9."],
    ["^(\\d+/\\d+)：(.+?) 於 (\\S+) 其他 ([\\d,]+) 股（(直接|間接)持股）。 變動後持有 ([^，。]+?) 股(?:(，佔) ([^，。]+?)(%))?。 (原因：(?:增持|減持|轉讓|其他)?)(.*?)。$", "$1: $2: other change of $4 shares on $3 ($5). Holds $6 shares after the change$7$8$9.$10$11."],
    // ---- 股票名稱：英文名 + 中文尾巴 → 只留英文（放最後）（1 條）
    ["^((?!RM\\d)[A-Za-z][A-Za-z0-9 .&'()-]*[A-Za-z0-9)]) [一-鿿]+$", "$1"],
  ]
};
